CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_POSIX_THREADS=y
CONFIG_POSIX_FILE_SYSTEM=y
CONFIG_INPUT=y
CONFIG_INPUT_QUEUE_MAX_MSGS=128
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=3700000
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_DISPLAY=y
CONFIG_LOG_MODE_DEFERRED=n
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_INFO_COLOR_GREEN=y

# C++
CONFIG_CPP_RTTI=y
CONFIG_STD_CPP23=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_CBPRINTF_FP_SUPPORT=y
#CONFIG_GRVL_USE_STM32_DMA2D=n
