image: debian:stable
stages:
  - build
  - docs-build
  - docs-deploy

variables:
  SCALENODE_CPU: 2
  SCALENODE_RAM: 4096
  SCALENODE_DISK: 10
  CMAKE_BUILD_TYPE: Release
  DEBIAN_FRONTEND: noninteractive

.build:
  stage: build
  before_script:
    - apt update -qqy
    - apt install -qqy file git gcc g++ nasm cmake libz-dev libjpeg-dev libpng-dev libtinyxml2-dev duktape-dev

# Build with provided dependencies
build_vendored:
  extends: .build
  script:
    - cmake -B build -DGRVL_STATIC=Y -DGRVL_SHARED=N
    - cmake --build build
    - ls -lh build/libgrvl*
    - file build/libgrvl*

# Build with libraries from debian stable
build_stable:
  extends: .build
  script:
    - apt install -qqy libdrm-dev pkg-config
    - cmake -B build -DGRVL_STATIC=N -DGRVL_SHARED=Y -DGRVL_LINUX_NATIVE=Y -DUSE_SYSTEM_LIBRARIES=Y
    - cmake --build build
    - ls -lh build/libgrvl*
    - file build/libgrvl*

# Build with new libraries from archlinux
build_latest:
  extends: .build
  image: archlinux:base
  before_script:
    - pacman -Syu --noconfirm git gcc make cmake zlib libjpeg-turbo libpng tinyxml2 duktape libdrm pkgconf
  script:
    - cmake -B build -DGRVL_STATIC=N -DGRVL_SHARED=Y -DGRVL_LINUX_NATIVE=Y -DUSE_SYSTEM_LIBRARIES=Y
    - cmake --build build
    - ls -lh build/libgrvl*
    - file build/libgrvl*

.docs-build:
  stage: docs-build
  before_get_sources:
    - apt update -qqy
    - apt install -qqy cmake make git gcc g++ nasm libz-dev libjpeg-dev libpng-dev libtinyxml2-dev duktape-dev python3 python3-venv doxygen graphviz latexmk texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra libsdl2-dev --no-install-recommends

docs-build:
  extends: .docs-build
  before_script:
    - python3 -m venv docs/.venv
    - source docs/.venv/bin/activate
    - pip3 install -r docs/requirements.txt
  script:
    - source docs/.venv/bin/activate
    - cmake -S. -Bbuild -DBUILD_DOCS=Y
    - cmake --build build --target Sphinx_HTML Sphinx_PDF
    - cp build/sphinx/pdf/latex/*.pdf build/sphinx/html/
    - tar cf $CI_DOCS_ARCHIVE -C build/sphinx/html/ .
  artifacts:
    paths:
      - build/sphinx
      - $CI_DOCS_ARCHIVE
    when: always
  only:
    - main
    - merge_requests

docs-deploy:
  variables:
    GIT_STRATEGY: none
  dependencies:
    - docs-build
  stage: docs-deploy
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
  only:
    - main
    - merge_requests
